### ISSUE TITLE
Fails on some Overpass results with error: adding duplicated key '${k}' to RefElements

### ISSUE THREAD

**Issue by MurzNN** [tibetty/osm2geojson-lite#4]
For example we can get this overpass query:
```
[out:json] [timeout:180]; 
rel(59752);  map_to_area->.myArea; 
relation(area.myArea) 
  ['admin_level'='6'] 
  ['boundary'='administrative']; 
out geom;
```
And when we pass results of that query to `osm2geojson-lite` - we got an error:
```
lib/utils.js:92
throw `Error: adding duplicated key '${k}' to RefElements`;
^
Error: adding duplicated key 'way/29077729' to RefElements
```

**Comment by MurzNN** [comment]
Seems this is because this result have way `"ref": 29077729,` double times, but it is located in separate items of `elements` array (serial number 0 and 1), so this must not cause the error.

**Comment by MurzNN** [comment]
Also https://github.com/tyrasd/osmtogeojson script parses this output without errors.

**Comment by tibetty** [comment]
Thanks for raise up this issue.  I will follow it up this weekend.

**Comment by tibetty** [comment]
I've suppressed this ***maybe*** trivial exception, please check it again.

**Comment by tibetty** [comment]
I will close the issue by this weekend if you have no response @MurzNN

**Comment by tibetty** [comment]
Given there's no more response for the issue raiser, I closed it.

**Comment by MurzNN** [comment]
Sorry for long response, with recent versions this issue is magically fixed. If I roll back to version from December, 6 - issue is still here. So let keep this closed.

**Comment by tibetty** [comment]
Actually it's not a magic - I suppressed this i-think-it-is-an-error exception in the code...
