### ISSUE TITLE
Release on npm

### ISSUE THREAD

**Issue by francois2metz** [tibetty/osm2geojson-lite#7]
Hi !

It would be nice if the latest changes on this repository are released on a new npm version. This way, i could use it instead of relying on my fork.

Have a nice day

**Comment by tibetty** [comment]
Sure! Does this weekend work for you? If so I will do it this weekend - personally I way too busy in work days.

**Comment by francois2metz** [comment]
Hi! Sure, do it when you can! There is no rush.

**Comment by tibetty** [comment]
Thanks for your waiting, it's done!

**Comment by francois2metz** [comment]
Thanks!
